# Generated by Django 6.0.4 on 2026-04-23 22:46

import django.db.models.deletion
import django_couchbase_orm.db.backends.couchbase.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_beer_doc_type_brewery_doc_type_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleCredential',
            fields=[
                ('id', django_couchbase_orm.db.backends.couchbase.fields.CouchbaseAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_sub', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apple_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
